#!/usr/bin/perl -w
use strict;
use 5.010;

greet( "Fred" );
greet( "Barney" );

sub greet {
  my($name) = @_;
  state $also_here;
  print "Hi, $name! ";
  if (defined $also_here) {
    print "$also_here is also here!\n";
  } else {
    print "You are the first one here!\n";
  }
  $also_here = $name;
}